# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: dev

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "test"
  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - run: echo "build"
  scan:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - run: echo "scan"
  deploy-dev:
    runs-on: ubuntu-latest
    needs: [scan, build]
    steps:
      - run: echo "deploy dev"

